### ISSUE TITLE
Chat filtering not working 

### ISSUE THREAD

**Issue by Nexxol** [nopcan/TwitchModCenter#14]
### What happened?

When I click "add" nothing happens.

### Steps to reproduce

Go to chat filtering and try adding something 

https://user-images.githubusercontent.com/68960034/140799887-2a238d97-e7a6-4b53-9853-f8454ae8348f.mp4

### Version

3.0 (Beta)

**Comment by Itsfadixx** [comment]
Can confirm

**Comment by nopcan** [comment]
2447
