### ISSUE TITLE
Chat restrictions bar still appears even after being disabled

### ISSUE THREAD

**Issue by NBruderman** [nopcan/TwitchModCenter#15]
### What happened?

I'm using a galaxy note 8, and since version 11.3.0 (2.13a) the chat restrictions banner wouldn't dissappear most of the time. Once in a while it would disappear, but would re appear when changing the screen from portrait to landscape and vice versa. This bug is still present in the latest beta (the latest version of 3.0)

https://user-images.githubusercontent.com/6445601/141059832-79c7291c-5f6b-4f38-90e9-0bb92c552700.mp4

### Steps to reproduce

1. Open a stream.
2. Check if the bar is hidden
3. If it is hidden, switch to landscape mode
4. The bar is visible again

### Version

3.0 (Beta)

**Comment by nopcan** [comment]
Fixed in 2447
