### ISSUE TITLE
Follower emotes

### ISSUE THREAD

**Issue by AhmedMekheimer** [nopcan/TwitchModCenter#23]
### What happened?

When i enable follower emotes, some spaces between words and emotes appear.

![Screenshot_20211222-233658](https://user-images.githubusercontent.com/76169566/147158032-4ab0921e-decb-4b82-b03d-ed004236773e.jpg)

As you can see in the image, me (ahmedkhaledmekh) copy pasted the same text but it got some spaces in it which i didn't type. 

This only happens when i enable follower emotes.

Thank you so much guys for this app honestly. 
xqcL ♥️♥️

### Steps to reproduce

Enable Follower emotes 

Type a sentence in chat 

It has spaces between every word 

### Version

3.1 (Beta)

**Comment by nopcan** [comment]
Fixed in 3.1a
