### ISSUE TITLE
( feature request)  A setting to change the 3 tabs to the top

### ISSUE THREAD

**Issue by Itsfadixx** [nopcan/TwitchModCenter#26]
### Describe the solution you'd like

I just wish  if there was a feature that changes the
 
following               Discover                Browse

To the top of the screen,  instead at the bottom 

### Why is this needed?

Because its better for chatting, Its annoying randomly clicking the tabs and the chat is gone , So this feature is very  needed 

### Additional context

![IMG_20211223_195038_707](https://user-images.githubusercontent.com/89106726/147270188-ab4a7350-2f6e-4f95-a684-0ecd9d837ae2.jpg)

**Comment by nopcan** [comment]
Added in 3.1a
