### ISSUE TITLE
[Feature Request] Recently used emotes for third-party ones

### ISSUE THREAD

**Issue by gimmeamin** [nopcan/TwitchModCenter#31]
### Describe the solution you'd like

Basically, the recently used emote section only detect the emotes from the official twitch emotes. But I want to have it also show for third party ones like bttv emotes and such.

The next best thing, is by manually adding the emotes to favorites. However, you still need to scroll down for that, which makes the recently used section worthless; hence making it just a waste of space.

### Why is this needed?

It takes too long to scroll down and find the emotes. I would prefer if it is at the top, and already shows the emotes I mostly use.

### Additional context

If that's not possible, maybe another solution to this issue is by being able to hide/change the order of the emote sections.

For example, an option to completely get rid of the recently used section. Or, to place the favorite emotes section at the top.

**Comment by nopcan** [comment]
Fixed on 3.2a
