### ISSUE TITLE
[Feature Request] Favourite emotes shortcut

### ISSUE THREAD

**Issue by JMort92** [nopcan/TwitchModCenter#39]
### Describe the solution you'd like

There are shortcuts to recently used, streamer, twitch, mods etc. It would be nice to have a shortcut to the favourite emotes that are available to select.

### Why is this needed?

Favourite emotes are found between streamer emotes and twitch emotes. It takes a long time to scroll to the favourite emotes from other shortcuts.

**Comment by nopcan** [comment]
Fav emotes now at the top
