### ISSUE TITLE
BetterTTV/FFZ/7TV >> Configure emotes not working properly

### ISSUE THREAD

**Issue by crsag** [nopcan/TwitchModCenter#9]
### What happened?

BetterTTV/FFZ/7TV >> Configure emotes not working properly

When you select ✅BTTV , ✅FFZ and ❎ 7TV. No emotes shows up . You have to select all of them to get custom emotes. 

### Steps to reproduce

1: mod settings
2: BetterTTV/FFZ/7TV tab
3: Configure emotes
4: Just select only one or two ( don't select all )
5: go to chat
6: there is no custom emotes in chat

### Version

3.0 (Beta)

**Comment by nopcan** [comment]
Fixed in 2447
